spring:
  datasource:
    #url: jdbc:h2:mem:test
    #driverClassName: org.h2.Driver
    #username: sa
    #password:
    url: jdbc:mysql://localhost:3306/intro_database
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #h2.console.enabled: true

